# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2


defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/Dynatrace/dynatrace-oneagent-operator


jobs:
  build:
    <<: *defaults
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          key: gopkg-{{ checksum "Gopkg.toml" }}
          paths:
              - /go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor
              - /go/pkg
      - run:
          name: Fetch dependencies
          command: dep ensure -v
      - save_cache:
          key: gopkg-{{ checksum "Gopkg.toml" }}
          paths:
              - /go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor
              - /go/pkg
      - run:
          name: Install godacov
          command: go get github.com/schrej/godacov
      - run:
          name: Run tests
          command: go test -cover -v $(go list ./... | circleci tests split)
      - run:
          name: Run tests with codacy upload
          command: godacov -t $CODACY_TOKEN -r ./coverage.out -c $CIRCLE_SHA1
      - run:
          name: Build binary
          command: go build -o ./build/_output/bin/dynatrace-oneagent-operator ./cmd/manager
      - persist_to_workspace:
          root: .
          paths:
            - LICENSE
            - build

workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
